In [7]:
# import
import pandas as pd

In [18]:
a = [3, 4, 78, 6]
b = [43, 42, 178, 76]
c = [38, 45, 728, 46]

In [31]:
arla = pd.DataFrame({'a': a,
                    'b': b,
                    'c': c})
arla

    a    b    c
0   3   43   38
1   4   42   45
2  78  178  728
3   6   76   46

In [32]:
d = arla['a']
e = list(d)
a == e

True

In [40]:
arla["row_mean"] = arla.mean(axis = 1)
arla

    a    b    c    row_mean
0   3   43   38   28.000000
1   4   42   45   30.333333
2  78  178  728  328.000000
3   6   76   46   42.666667

In [48]:
df = pd.read_csv("/work/KatrineMøllerAndersen#4971/E2026/psycholing_kma/Stroop-raw-over-the-years.csv")
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [49]:
df = df.drop(["Year"], axis = 1)
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int
0             4.16        6.76          4.45         4.65
1             4.35        7.73          4.78         4.46
2             3.60        7.00          4.00         3.50
3             3.90        9.03          4.60         6.30
4             4.22        9.98          6.83         6.24
..             ...         ...           ...          ...
200           4.77       10.00          5.66         6.24
201           4.61       12.80          6.87         9.55
202           4.79       10.72          5.64         7.25
203           4.41        8.87          6.70         6.70
204           5.50        9.80          6.20        21.70

[205 rows x 4 columns]

In [ ]:
df